SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT*p.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT p, FOOD_ORDER o
WHERE p.PRODUCT_ID=o.PRODUCT_ID
    AND DATE_FORMAT(o.PRODUCE_DATE, '%Y-%m')='2022-05'
GROUP BY 1
ORDER BY 3 DESC, 1;