SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i
JOIN ANIMAL_OUTS o
ON i.ANIMAL_ID=o.ANIMAL_ID
WHERE INSTR(i.SEX_UPON_INTAKE, 'Intact')>0
    AND (INSTR(o.SEX_UPON_OUTCOME, 'Spayed')>0 OR
         INSTR(o.SEX_UPON_OUTCOME, 'Neutered')>0)
ORDER BY 1;