WITH T AS (
    SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH,
        COUNT(DISTINCT i.USER_ID) AS PURCHASED_USERS
    FROM USER_INFO i
    JOIN ONLINE_SALE s
    ON i.USER_ID=s.USER_ID
    WHERE YEAR(i.JOINED)='2021'
    GROUP BY 1, 2
    ORDER BY 1, 2
)

SELECT *,
    ROUND(PURCHASED_USERS/
          (SELECT COUNT(*)
           FROM USER_INFO WHERE YEAR(JOINED)='2021'), 1) AS PUCHASED_RATIO
FROM T;