WITH TRUCK AS(
    SELECT HISTORY.HISTORY_ID, CAR.DAILY_FEE, (DATEDIFF(END_DATE, START_DATE)+1) DAYS,
    CASE 
        WHEN(DATEDIFF(END_DATE, START_DATE)+1) >= 90 THEN '90일 이상'
        WHEN(DATEDIFF(END_DATE, START_DATE)+1) >= 30 THEN '30일 이상'
        WHEN(DATEDIFF(END_DATE, START_DATE)+1) >= 7 THEN '7일 이상'
    END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR CAR
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
    ON CAR.CAR_ID = HISTORY.CAR_ID
    WHERE CAR.CAR_TYPE = '트럭'
)

SELECT TRUCK.HISTORY_ID, ROUND((TRUCK.DAILY_FEE * (1.0 - IFNULL(PLAN.DISCOUNT_RATE * 0.01, 0))) * TRUCK.DAYS, 0) FEE
FROM TRUCK
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON TRUCK.DURATION_TYPE = PLAN.DURATION_TYPE AND PLAN.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC