SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH,
    i.GENDER, COUNT(DISTINCT i.USER_ID) AS USERS
FROM ONLINE_SALE s
LEFT JOIN USER_INFO i
ON s.USER_ID=i.USER_ID
WHERE i.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;