SELECT CAR_ID,
    MAX(if('2022-10-16' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-%d') AND
       DATE_FORMAT(END_DATE, '%Y-%m-%d'),
       '대여중', '대여 가능')) AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1
ORDER BY 1 DESC;