with t AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY 1
)

SELECT t.CATEGORY, p.PRICE AS MAX_PRICE, p.PRODUCT_NAME
FROM FOOD_PRODUCT p
JOIN t
ON t.CATEGORY=p.CATEGORY AND t.MAX_PRICE=p.PRICE
ORDER BY 2 DESC;