with t AS (
    SELECT b.BOOK_ID, b.CATEGORY, a.AUTHOR_ID, a.AUTHOR_NAME, b.PRICE
    FROM BOOK b
    JOIN AUTHOR a
    ON a.AUTHOR_ID=b.AUTHOR_ID
)

SELECT t.AUTHOR_ID, t.AUTHOR_NAME, t.CATEGORY, SUM(t.PRICE*s.SALES) AS TOTAL_SALES
FROM t
JOIN BOOK_SALES s
ON t.BOOK_ID=s.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m')='2022-01'
GROUP BY 1, 3
ORDER BY 1, 3 DESC;