SELECT YEAR(SALES_DATE) YEAR,
MONTH(SALES_DATE) MONTH,
COUNT(DISTINCT O.USER_ID) PUCHASED_USERS,
ROUND(COUNT(DISTINCT O.USER_ID) / 
            (
                #2021에 가입한 전체 회원수 
                SELECT COUNT(DISTINCT USER_ID)
                FROM USER_INFO
                WHERE YEAR(JOINED) = 2021
            ), 1) AS PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH


