SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM PATIENT p
JOIN APPOINTMENT a
ON p.PT_NO=a.PT_NO
JOIN DOCTOR d
ON d.DR_ID=a.MDDR_ID
WHERE d.MCDP_CD='CS' AND a.APNT_CNCL_YN='N'
    AND DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d')='2022-04-13'
ORDER BY 6;