WITH RECURSIVE TIME AS(
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM TIME
    WHERE H<23
)
#SELECT * FROM TIME; 

SELECT H HOUR, COUNT(HOUR(DATETIME)) COUNT
FROM TIME 
LEFT JOIN ANIMAL_OUTS
ON H=HOUR(DATETIME)
GROUP BY H
